### PR TITLE
Device class improvements

### PR DESCRIPTION
**Pull request by apbarratt**
Resolves a few deprecation issues and adds various device classes to speed and distance sensors.  This allows for quick unit conversion within Home Assistant, meaning folk can select miles and mph as their distance and speed units without having to create template sensors to do this job for them.

Screenshot 2024-05-27 at 14 33 24

### CODE REVIEW

**Comment by apbarratt** [comment]
Screenshot 2024-05-27 at 14 37 17
Another screenshot showing various sensors now automatically converting to miles/mph/feet where desired.

**Comment by apbarratt** [comment]
[pokes @drakhart and @LeandroIssa] Wakey wakey! Don't you know you live to serve your non-paying job customers ;)
There's more PRs where this one came from on their way too if you can feedback on if I'm following this contribution guidelines correctly ;)

**Review by drakhart — APPROVED** [review]
Amazing, LGTM!

**Comment by drakhart** [comment]
I need to check what's up with the errrrr checks, it's been so long since I last pushed something that I don't even remember if they should be still working.

**Comment by apbarratt** [comment]
I've created issue an issue for this `master` vs `main` work:
https://github.com/drakhart/ha-super-soco-custom/issues/21

**Comment by apbarratt** [comment]
In the mean time, I've renamed `master` to `main` on my own fork and added a test PR and the workflow does indeed run, however there seems to be an import failure that I need to investigate.  I must figure out why it's happening, perhaps I need to bump some versioning somewhere because the thing it's complaining about is definitely there on latest :/

If it is a versioning thing, we will likely have to post a breaking change for folk using older versions of HA, though I'm not sure for how far back...

https://github.com/apbarratt/ha-super-soco-custom/actions/runs/9289237704/job/25562632711?pr=1

**Comment by apbarratt** [comment]
Seems we've got a number of upgrades required.  Python 3.10 is no longer supported by Home Assistant, so I've bumped that to 3.12 and I've also bumped the GitHub versions.  After that it seems distutils was dropped in Python 3.12, so I've updated the version of numpy to resolve that.  I've also tweaked the workflows to allow master as well as main for the time being (though apparently you need to approve workflows running from my repo), I'm guessing because of the tweaks to them.
The result is that the tests are now running, but they are failing on several suites due to some async testing error that I'm unfamiliar with:
ERROR tests/test_config_flow.py::test_failed_config_flow - AttributeError: 'async_generator' object has no attribute 'data'

**Comment by drakhart** [comment]
Thanks for the hard work looking into this, Andy. It looks fine at first glance, but I'd like to try this on my local env with some time during the weekend. Cheers.

**Comment by drakhart** [comment]
Notes:
- I've renamed `master` to `main`, and updated both the default branch and the branch protection rules. I'll do a clean up all over the code after merging this PR.
- `DEVICE_CLASSES` and `STATE_CLASS*` were deprecated as of 2021.12, while the min required version in this integration is `2022.3.0` so we should be safe here.
- I can't run the workflows locally: hassfest always complains `KeyError: 'codeowners'` though (apparently) it's set correctly. I'm clueless.
- Remote tests are failing because of a long due issue with `expected_lingering_timers`. I need to look into this, remember what was it about (I believe it had something to do with `pytest-homeassistant-custom-component`) and check if there's any solution.
- Because of the former two, I'm starting to remember why I haven't worked more often on this. 😄

Anyway this looks good, so LGTM and fingers crossed!

**Pull request merged**
